//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditerka
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogIngredients
    {
        public int IdCatalogIngredient { get; set; }
        public int IdCatalog { get; set; }
        public int IdIngredient { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Catalogs Catalogs { get; set; }
        public virtual Ingredients Ingredients { get; set; }
    }
}
