//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditerka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int IdReview { get; set; }
        public int IdUser { get; set; }
        public int IdCatalog { get; set; }
        public byte Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Catalogs Catalogs { get; set; }
        public virtual Users Users { get; set; }
    }
}
